name: Uma Tracker - Top 100

on:
  schedule:
    - cron: '10 15 * * *' # Runs at 11:10 PM Manila Time (15:10 UTC)
  workflow_dispatch:      # Allows you to click "Run Workflow" manually

jobs:
  scrape:
    # This tells GitHub to run the code on your PC, not their blocked servers
    runs-on: self-hosted 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Stealth Sync
        # We use 'python' directly since it's already on your PC
        # Running Ranks 1 to 20 as a test
        run: python main.py 0 20
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}

      - name: Cool Down
        # Jitter to keep the residential IP reputation clean
        run: |
          python -c "import time, random; time.sleep(random.randint(60, 120))"
